#!/usr/bin/env zsh

set -eu

store=$HOME/tmp/shuffle-to-tmp
mkdir -p "$store"

hash16() {
    md5sum <<< "$1" | dd bs=16 count=1 2> /dev/null
}

for file in "$@"; do
    stored="$store/$(hash16 $(dirname "$file"))-$(basename "$file")"

    if ! ([ -e "$file" ] || [ -e "$stored" ]); then
        echo "$file nor $stored exist, skipping"
        continue
    fi

    if [ -e "$file" ]; then
        mv -v "$file" "$stored"
    else
        mv -v "$stored" "$file"
    fi
done
