#!/usr/bin/env sh

# show us one full screen of contents from stdin

if [ -n "$r" ]; then
    cmd=head
else
    cmd=tail
fi

$cmd -n$(( $(tput lines) - 3)) | \
    sed 's/	/    /g' | \
    cut -c-$(tput cols)
